---
title: "Assignment3"
author: "xiaoyi"
date: "10/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1 
- random experiment: is a procedure
1) has a well-defined set of possible outcomes
2) could be repeated arbitrarily many times
- event
is a set of possible outcomes
- sample space is the set of all possible outcomes

# 2.1
```{r}
library(tidyverse)

impute_by_median<-function(x){
  
  md<-median(x,na.rm=1)
  
  impute_f<-function(z){
    if(is.na(z)){
      return(md)
    }else{
      return(z)
    }
  }
    return(map_dbl(x,impute_f))
}

v<-c(1,2,NA,4)
impute_by_median(v)


x<-seq(0,10,0.1)

y<-5*x + 1

df_xy<-data.frame(x,y)

df_xy%>%head(5)    

df_xy%>%
mutate(z=map2_dbl(x,y,~.x+.y))%>%
head(5)

sometimes_missing<-function(index,value){
  if(index %% 5 ==0){
    return (NA)
    }else{
      return (value)
    }
  }


#sometimes_missing(14,25)
#sometimes_missing(15,25)

# how to use row_number() to extract the index?
df_xy_missing<-df_xy%>%
    mutate(y=map2_dbl(x,y,~sometimes_missing(match(.y,y),.y)))

#df_xy_missing%>%head(10)

df_xy_impute<-df_xy_missing%>%
  mutate(y=impute_by_median(y))
 
df_xy_impute%>%head(10)
  
df_xy<-df_xy%>%
mutate(source="original")
df_xy_missing<-df_xy_missing%>%
mutate(source="corrupted")
df_xy_impute<-df_xy_impute%>%
mutate(source="imputed")

df_combined<-rbind(df_xy,df_xy_missing,df_xy_impute)
df_combined%>% head()

ggplot(df_combined,aes(x=x,y=y,color=source))+
  geom_point()+
  facet_wrap(~source)+
  geom_smooth(method='lm')


```
# 2.2
```{r}
library(tidyverse)
library(readxl)

#folder_path<-"~/Desktop/"
folder_path<-"~/RstudioProjects/xy_firstRProject/"
file_name<-"HockeyLeague.xlsx"

file_path<-paste(folder_path,file_name,sep="")

wins_data_frame<-read_excel(file_path,sheet="Wins")



wins_tidy<- wins_data_frame %>%
#  rename("Team"=colnames(wins_data_frame[1])) %>%
  rename("Team"=c(1)) %>%
  pivot_longer(!Team,names_to ="Year",values_to = "Wins" )%>%
  separate(Wins,into=c("Wins","Total"),sep="of")%>%
  transform(Wins = as.integer(Wins))%>%
  transform(Total = as.integer(Total))
  
  
#  transform(wins_tidy$Wins<-as.integer(wins_tidy$Wins))
#  transform(wins_tidy$Total<-as.integer(wins_tidy$Total))


  
wins_tidy

#wins_tidy%>% dim()
#wins_tidy%>% head(5) 


folder_path<-"~/RstudioProjects/xy_firstRProject/"
file_name<-"HockeyLeague.xlsx"

file_path<-paste(folder_path,file_name,sep="")

losses_data_frame<-read_excel(file_path,sheet="Losses")
losses_tidy<-losses_data_frame%>%
  rename("Team"=c(1))%>%
  pivot_longer(!Team,names_to ="Year",values_to = "Losses" )%>%
  separate(Losses,into=c("Losses","Total"),sep="of") 

losses_tidy

  transform(losses_tidy$Losses<-as.integer(losses_tidy$Losses))
  transform(losses_tidy$Total<-as.integer(losses_tidy$Total))


hockey_df<-inner_join(wins_tidy,losses_tidy)%>%
  mutate(Draws=Total-Wins-Losses,Wins_rt=Wins/Total,Losses_rt=Losses/Total,Draws_rt=Draws/Total)

#???????? 
'hockey_df%>%
mutate(c("Wins_rt","Losses_r","Draw_rt")<-across(c("Wins","Losses","Draws"),~.x/"Total"))
  '

hockey_df %>%
  group_by(Team)%>%
  summarise(row_number=n(),across(c("Wins_rt","Losses_rt","Draws_rt"),
            list(mean=~mean(.x,na.rm=1),
                 md=~median(.x,na.rm=1))))%>%
  arrange(desc(Wins_rt_md))

```





