---
title: "Assignment2"
author: "xiaoyi"
date: "05/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1.3
```{r}
library(tidyverse)
library(Stat2Data)
data("Hawks")
hawksSmall<-drop_na(select(Hawks,Age,Day,Month,Year,CaptureTime,Species,Wing,Weight,Tail))
weight_hist<-ggplot(hawksSmall,aes(x=Weight))+
            xlab("Weight(gm)")+
            geom_histogram(binwidth=100)+
            ylab("Count")

weight_hist
```

# 1.4
```{r}
tail_density<-ggplot(hawksSmall,aes(x=Tail))+
              geom_density()+
              xlab("Tail(mm)")+
              ylab("Density")
tail_density 
tail_density<-ggplot(hawksSmall,aes(x=Tail))+
              geom_density(adjust=0.5)+
              xlab("Tail(mm)")+
              ylab("Density")
tail_density
tail_density<-ggplot(hawksSmall,aes(x=Tail))+
              geom_density(adjust=1)+
              xlab("Tail(mm)")+
              ylab("Density")
tail_density

ggplot(data=(hawksSmall),aes(x=Tail,color=Species))+
      xlab("Tail(mm)")+
      geom_density()+
      theme_bw()+
      ylab("density")


ggplot(hawksSmall,aes(x=Tail,color=Species,y=Species,fill=Species))+
      geom_violin()+
      theme_bw()+
      xlab("Tail(mm)")+
      ylab("Species")
      
```
# 1.5
aesthetics: Tail-horizontal position
            weight-vertical position
            Species-color
glyph is point

```{r}
ggplot(hawksSmall,aes(x=Tail,y=Weight,color=Species,shape=Species))+
      geom_point()+
      theme_bw()+
      xlab("Tail(mm)")+
      ylab("Weight(mm")
```

# 1.6
```{r}
tail_weight_plot <- ggplot(hawksSmall,aes(x=Tail,y=Weight,color=Species))+
      geom_point()+
      geom_smooth(formula = y ~ x, method="lm")+
      facet_wrap(~Species, scales = "free")+

      geom_text(data=data.frame(Species = c("RT")),aes(x=210,y=1850,label="The heaviest hawks"))

tail_weight_plot+geom_curve(data=data.frame(Species = c("RT")), aes(x=220,xend=209,y=1850,yend=2000),arrow = arrow(length = unit(0.5,"cm")),curvature = 0.1 )
```

# 2.1
```{r}

hSF<-Hawks%>%filter(Species=="RT"& Weight>=1000) %>% select(Wing,Weight,Tail)

head(hSF)
```
# 2.2
```{r}
hSF<-hSF %>% arrange(Wing)

head(hSF)
```
# 2.3

```{r}
species_code<-c("CH","RT","SS")
species_name_full<-c("Cooper's","Red-tailed","Sharp-shinned")
fullname_df<-data.frame(species_code,species_name_full)
fullname_df<-fullname_df%>%rename(Species=species_code)
hawksFullName<-Hawks%>%left_join(fullname_df)
hawksFullName<-hawksFullName%>%select(-Species)%>%rename(Species=species_name_full)
hawksFullName%>%select(Species,Wing,Weight)%>%head(7)
head(hawksFullName)
```

# 2.4
```{r}

hawks_BMI<-Hawks%>%mutate(bird_BMI=1000*Weight/Wing^2)%>%select(Species,bird_BMI)%>%arrange(desc(bird_BMI))%>%filter(bird_BMI<=100)

head(hawks_BMI)
ggplot(hawks_BMI,aes(x=bird_BMI,y=Species,fill=Species))+
      geom_violin()+
      xlab("Bird BMI")+
      ylab("Species")
      

```
# 2.5
```{r}
hawksFullName %>% 
    group_by(Species)%>%
    summarize(
        num_rows=n(),mn_wing=mean(Wing,na.rm=1),
        md_wing=median(Wing,na.rm=1),
        t_mn_wing=mean(Wing,trim=0.1,na.rm = 1),
        tail_wing_ration=mean(Wing/Tail,na.rm = 1)
    )

hawksFullName %>% 
  group_by(Species)%>%
  select( Wing, Weight, Culmen, Hallux, Tail, StandardTail,
  Tarsus,Crop)%>%
  summarize(
    across(everything(),~sum(is.na(.x)))
  )

```
# 3.1
```{r}
Hawks %>%
    summarize(
      Wing_mean=mean(Wing,na.rm=1),
      Wing_t_mean=mean(Wing,trim=0.1,na.rm=1),
      Wing_med=median(Wing,na.rm=1),
      Weight_t_mean=mean(Weight,trim=0.1,na.rm=1),
      Weight_med=median(Weight,na.rm=1)
    )
Hawks %>%
  group_by(Species)%>%
    summarize(
      Wing_mean=mean(Wing,na.rm=1),
      Wing_t_mean=mean(Wing,trim=0.1,na.rm=1),
      Wing_med=median(Wing,na.rm=1),
      Weight_t_mean=mean(Weight,trim=0.1,na.rm=1),
      Weight_med=median(Weight,na.rm=1)
    )
```
# 3.2 a^2 x

# 3.3
```{r}
hal<-Hawks$Hallux # Extract the vector of hallux lengths
hal<-hal[!is.na(hal)] # Remove any nans

outlier_val<-100
num_outliers<-10
corrupted_hal<-c(hal,rep(outlier_val,times=num_outliers))

mean(hal)
mean(corrupted_hal)

num_outliers_vect<-seq(0,1000)
means_vect<-c()

for(num_outliers in num_outliers_vect){
corrupted_hal<-c(hal,rep(outlier_val,times=num_outliers))
means_vect<-c(means_vect,mean(corrupted_hal))
}

medians_vect<-c()
for(num_outliers in num_outliers_vect){
corrupted_hal<-c(hal,rep(outlier_val,times=num_outliers))
medians_vect<-c(medians_vect,median(corrupted_hal))
}

t_means_vect<-c()
for(num_outliers in num_outliers_vect){
corrupted_hal<-c(hal,rep(outlier_val,times=num_outliers))
t_means_vect<-c(t_means_vect,mean(corrupted_hal,trim=0.1))
}

df_means_medians<-data.frame(num_outliers=num_outliers_vect,
mean=means_vect,t_mean=t_means_vect,
median=medians_vect)

df_means_medians%>%
pivot_longer(!num_outliers, names_to = "Estimator", values_to = "Value")%>%
ggplot(aes(x=num_outliers,color=Estimator,
linetype=Estimator,y=Value))+
geom_line()+xlab("Number of outliers")

```
# 3.4
```{r}

ggplot(
  Hawks,
  aes(x=Species,y=Weight))+
  geom_boxplot()+
  xlab("Species")+
  ylab("Species")
  

num_outliers<-function(Weight){
  
  q25<-quantile(Weight,0.25)
  q75<-quantile(Weight,0.75)
  iq_range<-q75-q25
  outliers<-Weight[(Weight>q75+1.5*iq_range)|(Weight<q25-1.5*iq_range)]
  return(num)
}

Hawks%>%
  group_by(Species)%>%
  filter(!is.na(Weight))%>%
  summarize(num_outliers=num_outliers(Weight))

```

